"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var _06_Generics_1 = require("./06-Generics");
var _06_Generics_2 = require("./06-Generics");
var nums;
nums = new _06_Generics_1.List(1, 2, 3, 4, 5, 6, 8);
nums.add(7);
nums.remove(8);
var newData = nums.asArray();
console.log(newData);
var weekdays;
weekdays = new _06_Generics_1.List("Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Saturday");
weekdays.add("Friday");
weekdays.remove("Saturday");
weekdays.remove("Sunday");
console.log(weekdays.asArray());
var pair1;
pair1 = new _06_Generics_2.KeyValuePair(1, "One");
console.log(pair1.getKey());
console.log(pair1.getValue());
